#!/bin/bash

# Postinstall script for unsigned Electron app
# This script removes quarantine attributes to allow the app to run without code signing

APP_NAME="Compress.app"
INSTALL_DIR="/Applications"

# Check if the app was installed to Applications
if [ -d "$INSTALL_DIR/$APP_NAME" ]; then
    echo "Removing quarantine attributes from $APP_NAME..."
    
    # Remove quarantine attributes using xattr
    xattr -cr "$INSTALL_DIR/$APP_NAME"
    
    if [ $? -eq 0 ]; then
        echo "Successfully removed quarantine attributes from $APP_NAME"
        echo "The app should now run without code signing issues."
    else
        echo "Warning: Failed to remove quarantine attributes from $APP_NAME"
        echo "You may need to manually run: xattr -cr /Applications/$APP_NAME"
    fi
else
    echo "Warning: $APP_NAME not found in $INSTALL_DIR"
    echo "If you installed to a different location, manually run: xattr -cr /path/to/$APP_NAME"
fi

echo "Installation complete!"
